# direction: right
vars {
    d2-config {
        sketch: true
        center: true
        # layout-engine: elk
    }
}

Salesforce: "Salesforce Org" {
    direction: right
    Flow: "Scheduled Flow\n(Active Members Query)"
    NamedCredential: "Named Credential\n(HTTPS Auth to Google)"
    Salesforce -> Flow: triggers {
    }
    Flow -> NamedCredential: makes HTTP callout
}

Google: "Google Workspace" {
    GAS: "Google Apps Script Web App\n(Deployed via Google Drive)"
    GWS: "Google Workspace Admin SDK\n(Manage Users/OU)"
    OU: "\"IdP Users Only\" OU"
    
    GAS -> GWS: authenticates with domain-wide delegation
    GWS -> OU: updates user accounts
    OU <- GAS: \n• Create if new\n• Update if mismatched\n• Delete if missing
}

Salesforce.NamedCredential -> Google.GAS: sends list of active members
